packages:
- .
resolver: lts-18.27
compiler: ghc-8.10.7
# extra-include-dirs:
# - /home/jroper18/Documents/Projects/HaskellScrape/haskell-compilable/include

# extra-lib-dirs:
# - /home/jroper18/Documents/Projects/HaskellScrape/haskell-compilable/include

extra-deps:
- dir-traverse-0.2.3.0@sha256:adcc128f201ff95131b15ffe41365dc99c50dc3fa3a910f021521dc734013bfa,2137
